----- Versão PostgreSQL: 17

CREATE TABLE TB_CLIENTE (ID_CLIENTE SERIAL PRIMARY KEY,
						 NOME VARCHAR(500) NOT NULL,
						 ENDERECO VARCHAR(500) NOT NULL,
						 TELEFONE VARCHAR(15) NOT NULL,
						 EMAIL VARCHAR(100) NOT NULL
						 CHECK (EMAIL ~*'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')UNIQUE);

SELECT * FROM TB_CLIENTE;

CREATE TABLE TB_PRODUTOS (ID_PRODUTO SERIAL PRIMARY KEY,
						  NOME_PROD VARCHAR(500) NOT NULL,
						  DESCRICAO VARCHAR(500) NOT NULL,
						  PRECO DECIMAL(10,2) NOT NULL,
						  ESTOQUE DECIMAL(10,2) NOT NULL);

SELECT * FROM TB_PRODUTOS;

CREATE TABLE TB_VENDAS (ID_VENDA SERIAL PRIMARY KEY,
						ID_CLIENTE INT NOT NULL,
						ID_PRODUTO INT NOT NULL,
						QTY_ITEM DECIMAL(10,2) NOT NULL,
						FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
						FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTOS (ID_PRODUTO));

SELECT * FROM TB_VENDAS;

SELECT C.NOME AS "NOME DO CLIENTE",
	   P.DESCRICAO AS "PRODUTO",
	   V.QTY_ITEM AS "QUANTIDADE VENDIDA",
	   P.PRECO AS "PREÇO UNITARIO",
	   V.PRECO_TOTAL AS "PREÇO TOTAL"
FROM TB_VENDAS V
INNER JOIN TB_CLIENTE C ON C.ID_CLIENTE = V.ID_CLIENTE
INNER JOIN TB_PRODUTOS P ON P.ID_PRODUTO = V.ID_PRODUTO
WHERE 1=1
ORDER BY ID_VENDA;